####################### DEMONSTRATION OF INTEGRATION WITH CI PROVIDER WITH SAMPLE PARAMETERS ###########################
# Integration with CircleCI
#   1. Login to CI provide with Github
#   2. Select the repository where project source code exist.
#   3. Set up the config.yml file
#   4. Below are a few of the parameter used to run the tests in CI

version: 2.1
orbs:
  cypress: cypress-io/cypress@2
workflows:
  build:
    jobs:
      - cypress/run:
          name: End-to-end-tests
          requires:
            - cypress/install
          record: true # record results with Cypress Cloud
          parallel: true # split all specs across machines
          group: 'Chrome' # name this group "Chrome" on the dashboard
          command: npm run test
          store_artifacts: true
