####################### DEMONSTRATION OF INTEGRATION WITH CI PROVIDER WITH SAMPLE PARAMETERS ###########################
# Integration with CircleCI
#   1. Login to CI provide with Github
#   2. Select the repository where project source code exist.
#   3. Set up the config.yml file

version: 2.1
orbs:
  cypress: cypress-io/cypress@2
workflows:
  build:
    jobs:
      - cypress/run: # "run" job comes from "cypress" orb
        command: npm run test
